version: '3'
services:
  tensorflow:
    restart: always
    runtime: nvidia
    ports:
      - "8889:8888"
      - "12346:12346"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=2222
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - TF_GPU_ALLOCATOR=cuda_malloc_async
    volumes:
      - ../:/tf/aiffel
    build:
      context: .
      dockerfile: Dockerfile
    deploy:  # deploy 섹션에 GPU 사용 설정 추가
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

