version: '3'
services:
  tensorflow:
    restart: always
    ports:
      - "12345:8888"
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=1111
      - CUDA_VIsible_DEVICES=0
    volumes:
      - ../:/tf/aiffel
    build:
      context: .
      dockerfile: Dockerfile
    deploy:  # deploy 섹션에 GPU 사용 설정 추가
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

